name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        dnsdist: [ '17' ]
        config: [ 'full', 'doh', 'minimal', 'blacklist', 'split' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: add pdns user
      run: |
        sudo addgroup --system --gid 953 pdns
        sudo adduser --system --disabled-password --no-create-home -uid 953 --gid 953 pdns

    - name: Prepare config
      run: |
        mkdir $PWD/testconf/
        cp $PWD/examples/dnsdist-${{ matrix.config }}.yml $PWD/testconf/dnsdist.yml
        cp $PWD/testdata/dnsdist_docker.conf $PWD/testconf/dnsdist.conf
        cp $PWD/dnsdist_ootb.lua $PWD/testconf/dnsdist_ootb.lua
        cp -rf $PWD/dnsdist_ootb/ $PWD/testconf/
        cp $PWD/testdata/server.crt $PWD/testconf/cert.pem
        cp $PWD/testdata/server.key $PWD/testconf/key.pem
        cd $PWD/testconf/
        wget -nv https://raw.githubusercontent.com/dmachard/blocklist-domains/data/blocklist.cdb
        ls -lart $PWD

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d -p 5553:53/udp -p 5553:53/tcp --name=dnsdist --volume=$PWD/testconf/:/etc/dnsdist/conf.d/:z powerdns/dnsdist-${{ matrix.dnsdist }}
        dig -p 5553 www.github.com @127.0.0.1 +timeout=10 +tries=3 +retry=3 | grep NOERROR
