name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        dnsdist: [ '17' ]
        config: [ 'minimal' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: add pdns user
      run: |
        sudo addgroup --system --gid 953 pdns
        sudo adduser --system --disabled-password --no-create-home -uid 953 --gid 953 pdns

    - name: Deploy dnsdist docker image
      run: |
        cp $PWD/examples/dnsdist-${{ matrix.config }}.yml $PWD/dnsdist.yml
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/:/etc/dnsdist/conf.d/:z powerdns/dnsdist-${{ matrix.dnsdist }}
        dig -p 5553 www.github.com @127.0.0.1 +timeout=10 +tries=3 +retry=3 | grep NOERROR